name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone-down
        uses: actions/checkout@v2   
      - name: Build-app
        run: ci/build-app.sh
      - name: Unit-test-app
        run: ci/unit-test-app.sh